#!/usr/bin/env python3
"""Bake data/scripts/*.lua into src/scripts_gen.h as raw string literals (single executable, no loose files)."""
import glob, os, sys

os.chdir(os.path.join(os.path.dirname(__file__), ".."))
out = ["// Generated by tools/bake_scripts.py from data/scripts/*.lua. Do not edit.", "#pragma once", "",
       "inline const char* const kScripts[][2] = {"]
paths = sorted(glob.glob("data/scripts/*.lua"), key=lambda p: (os.path.basename(p) != "common.lua", p))
for p in paths:
    src = open(p, encoding="utf-8-sig").read()  # luaL_loadbuffer does not skip a BOM
    if ')LUA"' in src:
        sys.exit(f'{p}: contains the raw-string delimiter )LUA" — cannot bake')
    out.append(f'    {{"{os.path.basename(p)}", R"LUA({src})LUA"}},')
out += ["};", ""]
text = "\n".join(out)
dst = "src/scripts_gen.h"
if not os.path.exists(dst) or open(dst, encoding="utf-8").read() != text:
    open(dst, "w", encoding="utf-8").write(text)
print(f"baked {len(paths)} scripts")
