#!/usr/bin/env python3
"""Bake data/*.json into src/data_gen.h. CMake runs it before compiling (target `bake`)."""
import glob
import json

GRADE = {"I": 1, "II": 2, "III": 3, "IV": 4, "V": 5}
ELEMENTS = {"Wood", "Fire", "Earth", "Metal", "Water"}


def s(v):
    return json.dumps("" if v is None else v, ensure_ascii=False)


out = ["// Generated by tools/bake_data.py from data/*.json. Do not edit.", "#pragma once", '#include "data.h"', "",
       "namespace data {", "inline const YokaiDef kYokai[] = {"]
for f in sorted(glob.glob("data/yokai_[0-9]*.json")):
    y = json.load(open(f, encoding="utf-8"))
    if y["element"] not in ELEMENTS:
        raise SystemExit(f"{f}: element must be one of {sorted(ELEMENTS)}")
    st = y["stats"]
    sk = (y["skills"] + ["", "", "", ""])[:4]
    out.append(f'    {{{s(y["id"])}, {y["dex_number"]}, {s(y["name_ko"])}, {s(y["name_en"])}, {s(y["folklore_source"])}, '
               f'{"true" if "KOREAN" in y["origin"] else "false"}, {GRADE[y["grade"]]}, Element::{y["element"]}, '
               f'{st["hp"]}, {st["qi"]}, {st["attack"]}, {st["defense"]}, {st["speed"]}, '
               f'{{{", ".join(s(x) for x in sk)}}}, {s(y.get("trait"))}}},')
out += ["};", "inline const SkillDef kSkills[] = {"]
for f in sorted(glob.glob("data/skill_[0-9]*.json")):
    k = json.load(open(f, encoding="utf-8"))
    out.append(f'    {{{s(k["id"])}, {s(k["name_ko"])}, {k.get("power", 0)}, {k.get("qi_cost", 0)}, '
               f'{k.get("accuracy", 100)}, {s(k.get("status"))}}},')
out += ["};", "inline const ItemDef kItems[] = {"]
for it in json.load(open("data/items.json", encoding="utf-8")):
    out.append(f'    {{{s(it["id"])}, {s(it["name_ko"])}, {s(it["desc"])}, {it["price"]}, '
               f'{"true" if it["usable_in_battle"] else "false"}}},')
out += ["};", "inline const ArtifactDef kArtifacts[] = {"]
for a in json.load(open("data/artifacts/artifacts_sample.json", encoding="utf-8")):
    out.append(f'    {{{s(a["id"])}, {s(a["name_ko"])}, {s(str(a.get("buff")))}, {s(str(a.get("debuff")))}}},')
out += ["};", "}  // namespace data", ""]
open("src/data_gen.h", "w", encoding="utf-8").write("\n".join(out))
print("baked data")
