#!/usr/bin/env python3
"""Bake a BDF pixel font into src/font_data.h (glyph table + 16-bit row bitmaps).

Usage: python3 tools/bake_font.py <font.bdf> <out.h> <Prefix>
  e.g. tools/bake_font.py assets/fonts/Galmuri11.bdf src/font11_data.h Font11
Font: Galmuri11 by Lee Minseo, SIL OFL 1.1 (assets/fonts/Galmuri-OFL.txt).
"""
import sys

src, dst, pre = sys.argv[1], sys.argv[2], sys.argv[3]
glyphs, cur = [], None
for line in open(src, encoding="utf-8"):
    p = line.split()
    if not p:
        continue
    if p[0] == "STARTCHAR":
        cur = {"rows": []}
    elif cur is None:
        continue
    elif p[0] == "ENCODING":
        cur["cp"] = int(p[1])
    elif p[0] == "DWIDTH":
        cur["adv"] = int(p[1])
    elif p[0] == "BBX":
        cur["w"], cur["h"], cur["xo"], cur["yo"] = map(int, p[1:5])
    elif p[0] == "BITMAP":
        cur["bitmap"] = True
    elif p[0] == "ENDCHAR":
        if cur.get("cp", -1) >= 32 and cur["w"] <= 16:
            glyphs.append(cur)
        cur = None
    elif cur.get("bitmap"):
        v = int(p[0], 16)
        bits = len(p[0]) * 4
        cur["rows"].append((v << (16 - bits)) & 0xFFFF if bits <= 16 else v >> (bits - 16))

glyphs.sort(key=lambda g: g["cp"])
rows, table = [], []
for g in glyphs:
    table.append(f"{{0x{g['cp']:X},{g['adv']},{g['w']},{g['h']},{g['xo']},{g['yo']},{len(rows)}}}")
    rows.extend(g["rows"])

with open(dst, "w", encoding="utf-8") as f:
    f.write(f"// Generated by tools/bake_font.py from {src.split('/')[-1]} (Galmuri, SIL OFL 1.1). Do not edit.\n")
    f.write("#pragma once\n#include <cstdint>\n\n")
    f.write("#ifndef FONT_GLYPH_DEFINED\n#define FONT_GLYPH_DEFINED\n")
    f.write("struct FontGlyph { std::uint32_t cp; std::int8_t adv, w, h, xo, yo; std::uint32_t row; };\n#endif\n")
    f.write(f"constexpr int k{pre}GlyphCount = {len(table)};\n")
    f.write(f"inline const FontGlyph k{pre}Glyphs[] = {{\n")
    for i in range(0, len(table), 8):
        f.write(",".join(table[i:i + 8]) + ",\n")
    f.write(f"}};\ninline const std::uint16_t k{pre}Rows[] = {{\n")
    for i in range(0, len(rows), 24):
        f.write(",".join(f"0x{r:X}" for r in rows[i:i + 24]) + ",\n")
    f.write("};\n")
print(f"{len(table)} glyphs, {len(rows)} rows -> {dst}")
