#!/usr/bin/env python3
"""Bake Tiled maps (data/maps/*.tmj) into src/maps_gen.h. Fails the build on broken warps."""
import glob
import json
import sys

SOLID = set("#BRJSThHWGe~")
ts = json.load(open("data/maps/placeholder.tsj", encoding="utf-8"))
kind = {t["id"] + 1: next(p["value"] for p in t["properties"] if p["name"] == "kind") for t in ts["tiles"]}
props = lambda o: {p["name"]: p["value"] for p in o.get("properties", [])}
maps = {}
for f in sorted(glob.glob("data/maps/*.tmj")):
    m = json.load(open(f, encoding="utf-8"))
    mp = props(m)
    ground = next(l for l in m["layers"] if l["name"] == "ground")
    objs = next((l["objects"] for l in m["layers"] if l["type"] == "objectgroup"), [])
    maps[mp["id"]] = dict(name=mp["name_ko"], indoor=mp.get("indoor", False), w=m["width"], h=m["height"],
                          tiles="".join(kind[g] for g in ground["data"]),
                          objs=[(o["type"], int(o["x"]) // 16, int(o["y"]) // 16, o.get("name", ""), props(o)) for o in objs])
errors = []
for mid, m in maps.items():
    for t, x, y, name, p in m["objs"]:
        if t != "warp":
            continue
        dst = maps.get(p["to_map"])
        if not dst:
            errors.append(f"{mid}: warp to unknown map {p['to_map']}")
            continue
        tx, ty = p["to_x"], p["to_y"]
        if not (0 <= tx < dst["w"] and 0 <= ty < dst["h"]) or dst["tiles"][ty * dst["w"] + tx] in SOLID:
            errors.append(f"{mid}: warp target {p['to_map']}({tx},{ty}) is out of bounds or solid")
if errors:
    print("\n".join(errors))
    sys.exit(1)
c = lambda v: json.dumps(v, ensure_ascii=False)
out = ["// Generated by tools/bake_maps.py from data/maps/*.tmj. Do not edit.", "#pragma once", '#include "maps_api.h"', ""]
table = []
for mid, m in maps.items():
    npcs = [f'{{{c(n)}, {x}, {y}, {c(p.get("face", "D"))}[0], {c(p.get("sprite", ""))}, {c(p.get("talk_event", ""))}}}'
            for t, x, y, n, p in m["objs"] if t == "npc"]
    warps = [f'{{{x}, {y}, {c(p["to_map"])}, {p["to_x"]}, {p["to_y"]}, {c(p.get("face", "D"))}[0]}}'
             for t, x, y, n, p in m["objs"] if t == "warp"]
    trigs = [f'{{{x}, {y}, {c(p["event"])}, {"true" if p.get("once") else "false"}}}'
             for t, x, y, n, p in m["objs"] if t == "trigger"]
    for arr, typ, items in (("npcs", "NpcDef", npcs), ("warps", "WarpDef", warps), ("trigs", "TriggerDef", trigs)):
        out.append(f"inline const {typ} {arr}_{mid}[] = {{{', '.join(items) or '{}'}}};")
    table.append(f'{{{c(mid)}, {c(m["name"])}, {m["w"]}, {m["h"]}, {"true" if m["indoor"] else "false"}, {c(m["tiles"])}, '
                 f'npcs_{mid}, {len(npcs)}, warps_{mid}, {len(warps)}, trigs_{mid}, {len(trigs)}}}')
out += ["inline const MapDef kMaps[] = {", ",\n".join("    " + t for t in table), "};", ""]
open("src/maps_gen.h", "w", encoding="utf-8").write("\n".join(out))
print(f"baked {len(maps)} maps")
