#!/usr/bin/env python3
"""
Yokai Asset Pipeline for 108: Yin-Yang Chronicle (108: 음양견문록)
Converts AI-generated & Aseprite sprites into quantized, packed C++ headers & binaries.
"""

import os
import sys
import argparse
import numpy as np
from PIL import Image
from palette_quantizer import quantize_image, remove_isolated_pixels, PALETTES

# ---------------------------------------------------------
# Bit Packing & RLE Compression Routines
# ---------------------------------------------------------

def pack_2bit(indices_1d):
    """Packs an array of 0..3 indices into 4 pixels per byte."""
    packed = bytearray()
    for i in range(0, len(indices_1d), 4):
        b = 0
        for j in range(4):
            val = indices_1d[i + j] if (i + j < len(indices_1d)) else 0
            b |= ((val & 0x03) << (6 - j * 2))
        packed.append(b)
    return packed

def pack_4bit(indices_1d):
    """Packs an array of 0..15 indices into 2 pixels per byte (High nibble, Low nibble)."""
    packed = bytearray()
    for i in range(0, len(indices_1d), 2):
        high = indices_1d[i] & 0x0F
        low = (indices_1d[i + 1] & 0x0F) if (i + 1 < len(indices_1d)) else 0
        packed.append((high << 4) | low)
    return packed

def compress_rle_4bit(indices_1d):
    """
    RLE compresses 0..15 indexed pixels.
    Format per chunk: [RunLength (1..15) | ColorIndex (0..15)] = 1 byte.
    If run > 15, splits into multiple chunks.
    """
    compressed = bytearray()
    if len(indices_1d) == 0:
        return compressed

    curr_val = indices_1d[0] & 0x0F
    curr_run = 1

    for val in indices_1d[1:]:
        val = val & 0x0F
        if val == curr_val and curr_run < 15:
            curr_run += 1
        else:
            compressed.append((curr_run << 4) | curr_val)
            curr_val = val
            curr_run = 1
    compressed.append((curr_run << 4) | curr_val)
    return compressed

def decompress_rle_4bit(compressed_bytes):
    """Decompresses 4-bit RLE bytearray into 0..15 indices."""
    decompressed = []
    for b in compressed_bytes:
        run = (b >> 4) & 0x0F
        val = b & 0x0F
        decompressed.extend([val] * run)
    return decompressed

# ---------------------------------------------------------
# Asset Processor & C++ Header Generator
# ---------------------------------------------------------

def process_sprite(image_path, target_dims=None, palette='dancheong16', bit_depth=4, cleanup=True):
    """Loads an image, quantizes, cleans up, and returns packed bytes + metadata."""
    img = Image.open(image_path)
    if target_dims:
        img = img.resize((target_dims[0], target_dims[1]), Image.Resampling.NEAREST)

    quant_img, indices = quantize_image(img, palette_name=palette)
    if cleanup:
        indices = remove_isolated_pixels(indices)

    h, w = indices.shape
    flat_indices = indices.flatten()

    if bit_depth == 2:
        raw_packed = pack_2bit(flat_indices)
    else:
        raw_packed = pack_4bit(flat_indices)

    rle_packed = compress_rle_4bit(flat_indices)

    return {
        'width': w,
        'height': h,
        'total_pixels': w * h,
        'palette': palette,
        'bit_depth': bit_depth,
        'raw_bytes': raw_packed,
        'rle_bytes': rle_packed,
        'raw_size': len(raw_packed),
        'rle_size': len(rle_packed),
        'rle_ratio': len(rle_packed) / max(1, len(raw_packed)) * 100.0,
        'quantized_image': quant_img,
        'indices': flat_indices
    }

def generate_cpp_header(processed_assets, output_header_path, namespace="JoseonRPG::AssetGen"):
    """Emits an optimized C++17 header containing constexpr asset tables."""
    lines = [
        "// ===========================================================================",
        "// AUTO-GENERATED BY YOKAI ASSET PIPELINE - DO NOT MODIFY MANUALLY",
        "// 108: Yin-Yang Chronicle (108: 음양견문록) - 1.44MB Floppy Optimized",
        "// ===========================================================================",
        "#pragma once",
        "#include <cstdint>",
        "#include <array>",
        "",
        f"namespace {namespace} {{",
        ""
    ]

    total_raw_bytes = 0
    total_rle_bytes = 0

    for name, data in processed_assets.items():
        w, h = data['width'], data['height']
        bpp = data['bit_depth']
        raw_len = data['raw_size']
        rle_len = data['rle_size']
        total_raw_bytes += raw_len
        total_rle_bytes += rle_len

        lines.append(f"// Asset: {name} ({w}x{h}, {bpp}-bit, Raw: {raw_len}B, RLE: {rle_len}B, Saved: {100.0 - data['rle_ratio']:.1f}%)")
        lines.append(f"constexpr uint32_t {name.upper()}_WIDTH = {w};")
        lines.append(f"constexpr uint32_t {name.upper()}_HEIGHT = {h};")
        lines.append(f"constexpr uint32_t {name.upper()}_RAW_SIZE = {raw_len};")
        lines.append(f"constexpr uint32_t {name.upper()}_RLE_SIZE = {rle_len};")

        # Emit Raw Packed Array
        lines.append(f"constexpr uint8_t {name.upper()}_RAW_DATA[{raw_len}] = {{")
        chunk = []
        for i, b in enumerate(data['raw_bytes']):
            chunk.append(f"0x{b:02X}")
            if (i + 1) % 16 == 0 or (i + 1) == raw_len:
                lines.append("    " + ", ".join(chunk) + ("," if (i + 1) < raw_len else ""))
                chunk = []
        lines.append("};")
        lines.append("")

        # Emit RLE Packed Array
        lines.append(f"constexpr uint8_t {name.upper()}_RLE_DATA[{rle_len}] = {{")
        chunk = []
        for i, b in enumerate(data['rle_bytes']):
            chunk.append(f"0x{b:02X}")
            if (i + 1) % 16 == 0 or (i + 1) == rle_len:
                lines.append("    " + ", ".join(chunk) + ("," if (i + 1) < rle_len else ""))
                chunk = []
        lines.append("};")
        lines.append("")

    lines.append(f"// SUMMARY: Total Raw Footprint = {total_raw_bytes} B (~{total_raw_bytes/1024:.2f} KB)")
    lines.append(f"// SUMMARY: Total RLE Footprint = {total_rle_bytes} B (~{total_rle_bytes/1024:.2f} KB)")
    lines.append(f"}} // namespace {namespace}")
    lines.append("")

    with open(output_header_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))

    print(f"[Done] Generated C++ Header: '{output_header_path}'")
    print(f"       Assets Processed : {len(processed_assets)}")
    print(f"       Total Raw Bytes  : {total_raw_bytes} B ({total_raw_bytes/1024:.2f} KB)")
    print(f"       Total RLE Bytes  : {total_rle_bytes} B ({total_rle_bytes/1024:.2f} KB)")

# ---------------------------------------------------------
# Self-Test Validation Routine
# ---------------------------------------------------------

def run_self_test():
    """Runs a complete round-trip validation test."""
    print("=== RUNNING ASSET PIPELINE INTEGRITY SELF-TEST ===")
    
    # Generate a test 48x48 synthetic indexed pattern
    test_indices = np.random.randint(0, 16, size=(48, 48), dtype=np.uint8).flatten()
    
    # 1. Test 4-bit packing
    packed_4bit = pack_4bit(test_indices)
    assert len(packed_4bit) == (48 * 48) // 2, "4-bit packing size mismatch!"

    # 2. Test RLE compression round-trip
    rle = compress_rle_4bit(test_indices)
    decompressed = decompress_rle_4bit(rle)
    assert len(decompressed) == len(test_indices), f"Length mismatch: {len(decompressed)} vs {len(test_indices)}"
    assert (np.array(decompressed) == test_indices).all(), "Decompressed data content mismatch!"

    # 3. Test 2-bit packing
    test_2bit_indices = np.random.randint(0, 4, size=(16, 24), dtype=np.uint8).flatten()
    packed_2bit = pack_2bit(test_2bit_indices)
    assert len(packed_2bit) == (16 * 24) // 4, "2-bit packing size mismatch!"

    print("[PASS] 4-bit Packing, 2-bit Packing, and RLE Decompression 100% Verified!")

# ---------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Yokai Asset Pipeline - Ingestion & C++ Code Generator.")
    parser.add_argument("--test", action="store_true", help="Run internal integrity self-test.")
    parser.add_argument("-i", "--input", help="Single image or directory of images.")
    parser.add_argument("-o", "--output-header", help="Output C++ header file path.")
    parser.add_argument("-p", "--palette", choices=list(PALETTES.keys()), default="dancheong16",
                        help="Palette to use: dmg4, dancheong16, extended32")
    parser.add_argument("-b", "--bpp", type=int, choices=[2, 4], default=4, help="Bits per pixel (2 or 4).")
    parser.add_argument("--dims", nargs=2, type=int, metavar=('W', 'H'), help="Target dimensions (e.g. 48 48).")

    args = parser.parse_args()

    if args.test:
        run_self_test()
        return

    if not args.input:
        parser.print_help()
        return

    processed = {}
    if os.path.isfile(args.input):
        asset_name = os.path.splitext(os.path.basename(args.input))[0]
        dims = (args.dims[0], args.dims[1]) if args.dims else None
        res = process_sprite(args.input, target_dims=dims, palette=args.palette, bit_depth=args.bpp)
        processed[asset_name] = res
    elif os.path.isdir(args.input):
        dims = (args.dims[0], args.dims[1]) if args.dims else None
        for root, _, files in os.walk(args.input):
            for file in files:
                if file.lower().endswith(('.png', '.bmp', '.jpg', '.jpeg')):
                    file_path = os.path.join(root, file)
                    asset_name = os.path.splitext(file)[0]
                    res = process_sprite(file_path, target_dims=dims, palette=args.palette, bit_depth=args.bpp)
                    processed[asset_name] = res

    if args.output_header and processed:
        generate_cpp_header(processed, args.output_header)
    else:
        for name, data in processed.items():
            print(f"Processed '{name}': {data['width']}x{data['height']} ({data['bit_depth']}bpp) -> Raw: {data['raw_size']}B, RLE: {data['rle_size']}B (Saved {100.0 - data['rle_ratio']:.1f}%)")

if __name__ == "__main__":
    main()
